### Get home
GET http://localhost:3001/

### Get all songs
GET http://localhost:3001/songs

### Get song by id
GET http://localhost:3001/songs/1

### Create song
POST http://localhost:3001/songs

### Update song by id
PUT http://localhost:3001/songs/1

### Delete song by id
DELETE http://localhost:3001/songs/1

